language: node_js

node_js:
  - "10"

branches:
  only:
    - main

cache:
  yarn: true

before_install:
  - yarn global add vsce

jobs:
  include:
    - stage: "publish"
      script:
        - vsce package
        - vsce publish -p $TOKEN_VSCODE
